### ISSUE TITLE
Question: more info on how embedded LUA has been prepared

### ISSUE THREAD

**Issue by intonarumori** [szieke/embLua#3]
Thanks for the this repo it got me up and running for an STM32 project.

I'm trying to understand what exactly has to be modified on the LUA source files to make it work on an Embedded system.

### As I understand it:
- Add a custom heap allocator
- Slim down dependencies on `<time.h>` and `<locale.h>` and implement a custom random generator
- Slim down LUA libraries to the minimum
- Remove unneeded file handling functions

### These are the exact changes I observed:
- Remove the following files from the LUA distribution folder: `lcorolib.c`, `ldblib.c`, `liolib.c`, `loadlib.c`, `loslib.c`, `lua.c`, `lua.hpp`, `lutf8lib.c`, `lopnames.h`, `luac.c`, `Makefile`
- Modify the following files:
  - `lauxlib.c`: remove the following functions `getF`, `errFile`, `skipBOM`, `skipcomment`, `luaL_loadFilex`
  - `lauxlib.c`: modify `l_alloc`
  - `lauxlib.c`: modify `panic` (?)
  - `lauxlib.c`: modify `warnfcont`, `warnfon`
  - `lauxlib.h`: wrap with "extern C..."
  - `lbaselib.c`: remove `luaB_loadfile`, `dofilecont`, `luaB_dofile`, update `base_funcs`
  - `ldo.c`: update `luaD_throw` to use `luaAbort()` and enter an infinite loop (?)
  - `linit.c`: remove library references and add `LUA_WITH_MATH` option
  - `llex.c`: remove `<locale.h>` import
  - `lmathlib.h`: remove `<time.h>` import, substitute it with a random function
  -  `lmathlib.h`: include file content based on `LUA_WITH_MATH` define
  - `lobject.c`: remove `<locale.h>` import
  - `lstate.c`: remove `<time.h>` import, update `luai_makeseed` to use random function
  - `lstate.h`: remove `<signal.h>` import, update `l_signalT` to `int`
  - `lstrlib.h`: remove `<locale.h> import, make sure `min_expand` always returns a value
  - `ltable.h` use `long` on RENESAS, make sure `getgeneric`, `luaH_getshortstr` always return a value
  -  `ltablib.c`: remove `<time.h>` import, add pseudo-random function, make sure `partition` always returns a value
  - `lua.h`: add `extern C...`
  - `luaconf.h`: introduce `LUA_DECIMAL_POINT`, set up int types on STM32 (?)
  - `lualib.h`: add `extern C...`
  - `lvm.c`: replace `strcoll` with `strcmp`, make sure `l_strcmp` returns a value (?)
 

I'm assuming the return values are mostly to make the compiler happy.
Do you think I missed anything important? Can you comment on the (?) items?

Many thanks.

**Comment by szieke** [comment]
Hi,

lauxlib.c: modify panic (?) : I modified this because my implementations of the lua message functions (e.g. lua_writestringerror) do not support format strings

ldo.c: update luaD_throw to use luaAbort() and enter an infinite loop (?):  I replaced abort with luaAbort so the project can decide what a behaviour shall be implemented (in my examples this function is defined in the projct specific luaInterface.c)

luaconf.h: introduce LUA_DECIMAL_POINT, set up int types on STM32 (?) : The original implementation is based on C locales. Many microcontrollers do not support this. Therfore I changed it.

lvm.c: replace strcoll with strcmp, make sure l_strcmp returns a value (?): strcoll is based on C locales therfore I changed it to strcmp. l_strcmp returns a value now because some compilers generate a warning if not.

Regards
